server    {                      
  listen 8080;                   
  host localhost;     
  root  /Users/rboutaik/Desktop/webserv_push/;
               
  autoindex on;


    location / {                
      root /Users/rboutaik/Desktop/webserv_push/;          
      php-cgi           /Users/rboutaik/Desktop/webserv_push/;                     
      autoindex on;     
      upload_store  /Users/rboutaik/Desktop/webserv_push/;
      return 301 https://www.google.com;
      index index.html index2.html kbcdskc cskdbckds;
  }
 
   location /home/folder/ {                
      root /Users/rboutaik/Desktop/webserv_push/;          
      php-cgi           /Users/rboutaik/Desktop/webserv_push/;                     
      autoindex on;     
      upload_store  /Users/rboutaik/Desktop/webserv_push/;
      return 301 https://www.google.com;
    }
}


localhost:8080/home/index.html